"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Storage = exports.date = exports.getType = exports.random = exports.cookie = void 0;
var cookie_1 = require("./lib/cookie");
Object.defineProperty(exports, "cookie", { enumerable: true, get: function () { return cookie_1.cookie; } });
var getType_1 = require("./lib/getType");
Object.defineProperty(exports, "getType", { enumerable: true, get: function () { return getType_1.getType; } });
var random_1 = require("./lib/random");
Object.defineProperty(exports, "random", { enumerable: true, get: function () { return random_1.random; } });
var storage_1 = require("./lib/storage");
Object.defineProperty(exports, "Storage", { enumerable: true, get: function () { return storage_1.Storage; } });
var date_1 = require("./lib/date");
exports.date = date_1.default;
